title: Jekyll URL Shortener
description: This is a URL Shortener which uses Jekyll and GitHub Pages to function. Use it to more easily share links! This shortener is 100% furry friendly!
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

#source: repository: hlaueriksson/jekyll-url-shortener
